name: Hello world workflow

on: 
  push: 
    branches:
      - main
  pull_request: 
    branches: 
    - main
  workflow_dispatch:

jobs: 
  hello: 
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v2
    - name: hello world
    - run: echo "Hello World Rohit"
    - shell: bash

  goodbye: 
    runs-on: ubuntu-latest
    steps:
    - name: Good Bye Darling
    - run : echo "Good Bye Darling"
    - shell: bash